### ISSUE TITLE
Travis builds are currently erroring due to an issue in Cask

### ISSUE THREAD

**Issue by lddubeau** [ananthakumaran/typescript.el#71]
The problem seems to be in Cask (https://github.com/cask/cask/issues/420) or in code that Cask depends on (https://github.com/melpa/package-build/issues/17).

The upshot for us is that as long as the issue is not resolved, our Travis builds are going to end with an error.

[Here's an example](https://travis-ci.org/lddubeau/typescript.el/jobs/358360135) of what it looks like.

**Comment by josteink** [comment]
That sucks, but I guess there's not much we can do about it. Apart from waiting it out, right?

Good thing bringing it to our attention though, otherwise this could quite easily become a point of confusion :)

**Comment by lddubeau** [comment]
Yeah, I wanted folks to be aware of the issue. Luckily, the Cask issue report I linked to was already filed. Otherwise, I would have been at a loss to figure out what's going on.

When I run into problems like this one, and I already have a good amount of knowledge about the piece of software that is failing, I try to fix it myself, but the extent of my knowledge of Cask is minuscule, and I cannot at the moment justify the time expense of becoming proficient enough with Cask to solve this problem, so I'm certainly going to wait it out.

**Comment by lddubeau** [comment]
It seems fixed now.

**Comment by anildigital** [comment]
@lddubeau still this issue is not resolved https://github.com/cask/cask/issues/420

**Comment by lddubeau** [comment]
@anildigital I closed this issue because I was no longer getting errors on Travis when running the tests for this project. There could be any number of reasons the Cask issue is still open: they forgot to close it, a change occurred that did not *completely* take care of the problem, though it was enough to fix the issue *for this project*, etc. Ultimately though, if our tests suite works, then there's no problem *for us*, and nothing to fix.

Did you run this project's test suite and got an error again? If yes, then please comment with a link to the Travis session's log.
